name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4 # Actualizado de v3 a v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4 # Actualizado de v3 a v4
        with:
          node-version: '20' # Usamos una versión estable

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar a Surge.sh
        # Asegúrate de que este nombre sea único
        run: surge ./ --domain tu-nombre-unico-2026.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}