name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar a Surge.sh
        # CAMBIA 'tu-nombre-unico' por algo personalizado para tu tarea
        run: surge ./ --practica-hidekel-itla.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}